spring.application.name=QuickTix
spring.threads.virtual.enabled=true

# Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.syntax-highlight.theme=monokai
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.default-models-expand-depth=-1

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

payment.gateway.provider=stripe

# Stripe Configuration
stripe.api.key=${STRIPE_SECRET_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}

#Paystack Configuration
paystack.secret.key=${PAYSTACK_SECRET_KEY}

#Caching TTL for Redis (300000ms which is 5 minutes)
spring.cache.redis.time-to-live=300000

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
#classpath:db/migration is the default btw
spring.flyway.locations=classpath:db/migration

rate-limit.ip.capacity=150
rate-limit.ip.refill=60
rate-limit.ip.interval=1

rate-limit.user.capacity=60
rate-limit.user.refill=30
rate-limit.user.interval=1

rate-limit.hold-seat.capacity=5
rate-limit.hold-seat.refill=5
rate-limit.hold-seat.interval=1
