# Profile activation
server.port=8081

## H2 Database (Local Only)
#spring.datasource.url=jdbc:h2:mem:quicktix
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#
## JPA / Hibernate (Local Only)
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Database (External)
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=password

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# RabbitMQ Configuration (Points to NotifyHub's local broker)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# QuickTix's Producer Configuration for NotifyHub
app.rabbitmq.exchange=notifyhub_delayed_exchange
app.rabbitmq.routing-key=notifications.routing.key
