# PostgreSQL Database (External)
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=password

# To choke the DB
spring.datasource.hikari.maximum-pool-size=10

# RabbitMQ Configuration (Points to NotifyHub's local broker)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# QuickTix's Producer Configuration for NotifyHub
app.rabbitmq.exchange=notifyhub_delayed_exchange
app.rabbitmq.routing-key=notifications.routing.key
