server.port=${server.port:9999}
server.tomcat.threads.max=500
server.tomcat.accept-count=2000
spring.threads.virtual.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=password

spring.datasource.hikari.maximum-pool-size=100
spring.datasource.hikari.minimum-idle=20
spring.datasource.hikari.connection-timeout=20000

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
app.rabbitmq.exchange=notifyhub_delayed_exchange
app.rabbitmq.routing-key=notifications.routing.key

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.redis.time-to-live=300000

jwt.secret=LoadTestingSuperSecretKeyThatIsAtLeast32BytesLongForHS256Algorithm
jwt.expiration=3600000
payment.gateway.provider=paystack
paystack.secret.key=sk_test_k6_load_testing_secret_key_override

rate-limit.ip.capacity=500000
rate-limit.ip.refill=500000
rate-limit.ip.interval=60

rate-limit.user.capacity=100000
rate-limit.user.refill=100000
rate-limit.user.interval=60

rate-limit.hold-seat.capacity=10
rate-limit.hold-seat.refill=10
rate-limit.hold-seat.interval=60

logging.level.root=WARN
logging.level.io.github.kxng0109=ERROR