package io.github.kxng0109.quicktix.service.gateway.dto;

import lombok.Builder;

/**
 * Represents the response returned after initializing a payment session with an external payment gateway.
 * <p>
 * This record provides key data necessary for the continuation of the payment flow, including a secure client token
 * that allows the frontend to redirect the user to the gateway (e.g., an authorization URL) and a unique
 * transaction ID for tracking and reconciliation purposes.
 *
 * <p><strong>Usage:</strong>
 * <ul>
 *     <li>The {@code clientSecret} field typically holds sensitive credentials like a session token or URL used
 *     by the client to continue payment.</li>
 *     <li>The {@code transactionId} field is a unique string generated by the payment gateway to identify the transaction.</li>
 * </ul>
 *
 * <p>Instances of this record are immutable and can be instantiated using the {@link Builder @Builder} pattern.
 */
@Builder
public record GatewayInitializationResponse(
		String clientSecret,
		String transactionId
) {
}
