CREATE TABLE bookings
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id           BIGINT                                  NOT NULL,
    event_id          BIGINT                                  NOT NULL,
    status            VARCHAR(255)                            NOT NULL,
    booking_reference VARCHAR(255)                            NOT NULL,
    total_amount      DECIMAL(10, 2)                          NOT NULL,
    version           INTEGER,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_bookings PRIMARY KEY (id)
);

CREATE TABLE events
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                  VARCHAR(255)                            NOT NULL,
    description           TEXT,
    venue_id              BIGINT                                  NOT NULL,
    event_start_date_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    event_end_date_time   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    ticket_price          DECIMAL(10, 2)                          NOT NULL,
    status                VARCHAR(255)                            NOT NULL,
    created_at            TIMESTAMP WITHOUT TIME ZONE,
    updated_at            TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

CREATE TABLE payments
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    booking_id            BIGINT                                  NOT NULL,
    amount                DECIMAL(10, 2)                          NOT NULL,
    status                VARCHAR(255)                            NOT NULL,
    idempotency_key       VARCHAR(255)                            NOT NULL,
    gateway_token         VARCHAR(255),
    payment_method        VARCHAR(255)                            NOT NULL,
    transaction_reference VARCHAR(255),
    paid_at               TIMESTAMP WITHOUT TIME ZONE,
    created_at            TIMESTAMP WITHOUT TIME ZONE,
    updated_at            TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_payments PRIMARY KEY (id)
);

CREATE TABLE seats
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id        BIGINT                                  NOT NULL,
    seat_number     INTEGER,
    row_name        VARCHAR(255),
    seat_status     VARCHAR(255)                            NOT NULL,
    held_at         TIMESTAMP WITHOUT TIME ZONE,
    held_by_user_id BIGINT,
    booking_id      BIGINT,
    version         INTEGER,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_seats PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name    VARCHAR(255)                            NOT NULL,
    last_name     VARCHAR(255)                            NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password_hash VARCHAR(255)                            NOT NULL,
    role          VARCHAR(255)                            NOT NULL,
    phone_number  VARCHAR(15),
    is_active     BOOLEAN                                 NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE venues
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    address        VARCHAR(500)                            NOT NULL,
    city           VARCHAR(255)                            NOT NULL,
    total_capacity INTEGER                                 NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_venues PRIMARY KEY (id)
);

ALTER TABLE bookings
    ADD CONSTRAINT uc_bookings_booking_reference UNIQUE (booking_reference);

ALTER TABLE payments
    ADD CONSTRAINT uc_payments_booking UNIQUE (booking_id);

ALTER TABLE payments
    ADD CONSTRAINT uc_payments_idempotency_key UNIQUE (idempotency_key);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

CREATE INDEX idx_event_status_date ON events (status, event_start_date_time);

CREATE INDEX idx_seat_event_status ON seats (event_id, seat_status);

ALTER TABLE bookings
    ADD CONSTRAINT FK_BOOKINGS_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id);

ALTER TABLE bookings
    ADD CONSTRAINT FK_BOOKINGS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE events
    ADD CONSTRAINT FK_EVENTS_ON_VENUE FOREIGN KEY (venue_id) REFERENCES venues (id);

ALTER TABLE payments
    ADD CONSTRAINT FK_PAYMENTS_ON_BOOKING FOREIGN KEY (booking_id) REFERENCES bookings (id);

ALTER TABLE seats
    ADD CONSTRAINT FK_SEATS_ON_BOOKING FOREIGN KEY (booking_id) REFERENCES bookings (id);

ALTER TABLE seats
    ADD CONSTRAINT FK_SEATS_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id);

ALTER TABLE seats
    ADD CONSTRAINT FK_SEATS_ON_HELD_BY_USER FOREIGN KEY (held_by_user_id) REFERENCES users (id);