CREATE TABLE seat_rows
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    row_order  INTEGER                                 NOT NULL,
    section_id BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_seat_rows PRIMARY KEY (id)
);

CREATE TABLE sections
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description TEXT                                    NOT NULL,
    capacity    BIGINT                                  NOT NULL,
    price       DECIMAL(10, 2)                           NOT NULL,
    event_id    BIGINT                                  NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_sections PRIMARY KEY (id)
);

ALTER TABLE seats
    ADD price DECIMAL(10, 2);

ALTER TABLE seats
    ADD row_id BIGINT;

ALTER TABLE seats
    ALTER COLUMN price SET NOT NULL;

ALTER TABLE seats
    ALTER COLUMN row_id SET NOT NULL;

ALTER TABLE seats
    ADD CONSTRAINT FK_SEATS_ON_ROW FOREIGN KEY (row_id) REFERENCES seat_rows (id);

ALTER TABLE seat_rows
    ADD CONSTRAINT FK_SEAT_ROWS_ON_SECTION FOREIGN KEY (section_id) REFERENCES sections (id);

ALTER TABLE sections
    ADD CONSTRAINT FK_SECTIONS_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id);

ALTER TABLE seats
    DROP COLUMN row_name;

ALTER TABLE events
    DROP COLUMN ticket_price;