package io.github.kxng0109.quicktix.service.gateway;

import io.github.kxng0109.quicktix.entity.Payment;
import io.github.kxng0109.quicktix.service.gateway.dto.GatewayInitializationResponse;
import org.springframework.context.annotation.Primary;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Service;

import java.util.Random;
import java.util.UUID;

@Service
@Profile({"test", "mock-stress-test"})
@Primary
public class MockPaymentGateway implements PaymentGateway {

    private final Random random = new Random();

    /**
     * @param payment the internal payment record to be processed
     * @return a {@link GatewayInitializationResponse} containing the secure client token (e.g., Stripe Client Secret)
     * as a String and the ID of the transaction generated by the payment gateway.
     */
    @Override
    public GatewayInitializationResponse initializePayment(Payment payment) {
        return new GatewayInitializationResponse("clientSecret", UUID.randomUUID().toString());
    }

    /**
     * Attempts to refund a transaction on the provider's side.
     *
     * @param transactionReference the unique transfer reference used for getting the status of the transfer
     *                             from the payment gateway provider
     * @return either true or false
     */
    @Override
    public boolean refundTransaction(String transactionReference) {
        return random.nextBoolean();
    }
}
